name: Package and Release Chrome Extension

on:
  push:
    branches: [ main ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.set_tag.outputs.release_tag }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set release tag and timestamp
      id: set_tag
      run: |
        timestamp=$(date -u +"%d-%m-%Y_%H-%M-%S")
        tag="SRText_${timestamp}"
        echo "release_tag=$tag" >> $GITHUB_OUTPUT
        echo "timestamp=$timestamp" >> $GITHUB_ENV

    - name: Create ZIP package
      run: |
        zip -r SRText.zip manifest.json readerView.js style.css

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.set_tag.outputs.release_tag }}
        release_name: ${{ steps.set_tag.outputs.release_tag }}
        body: |
          # Sparx Reader Text Viewer ${{ env.timestamp }}

          This is the latest version.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./SRText.zip
        asset_name: SRText.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
